ALTER TABLE reservations
  ADD COLUMN IF NOT EXISTS motorhome_class_a BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE reservations
  ADD COLUMN IF NOT EXISTS motorhome_class_c BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE reservations
  ADD COLUMN IF NOT EXISTS motorhome_with_tow BOOLEAN NOT NULL DEFAULT FALSE;
